# Generated by Django 6.0 on 2026-09-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('text', 'author', 'category'), name='unique_joke_text_author_category')],
            },
        ),
    ]
