# Generated by Django 6.0 on 2026-09-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techJokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('n_shares', models.IntegerField()),
                ('date_acquired', models.DateField()),
            ],
            options={
                'db_table': 'my_stocks',
            },
        ),
        migrations.CreateModel(
            name='NewlyAcquiredStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('n_shares', models.IntegerField()),
                ('date_acquired', models.DateField()),
            ],
            options={
                'db_table': 'newly_acquired_stocks',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quote_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'stock_prices',
            },
        ),
    ]
